version: '3'

tasks:
  default:
    desc: List the available tasks
    aliasses: ['help']
    cmds:
      - task -l

  install:
    desc: Run poetry install
    cmds:
      - poetry install

  test:
    desc: Run pytest
    cmds:
      - poetry run pytest

  format:
    desc: Format the code
    aliases: ["ruff"]
    cmds:
      - poetry run ruff format
      - poetry run ruff check --fix
